package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	profile "terraform-provider-fortiappseccloud/internal/generator/profile/waf"
)

const generatedMarker = "Code generated by cmd/wafdocgen; DO NOT EDIT."

func main() {
	root := flag.String("root", ".", "repository root containing reviewed WAF examples")
	flag.Parse()
	if flag.NArg() != 0 {
		fatalf("unexpected positional arguments: %v", flag.Args())
	}

	overridesJSON, err := os.ReadFile(filepath.Join(*root, "internal", "generator", "profile", "waf", "overrides.json"))
	if err != nil {
		fatalf("read reviewed WAF overrides: %v", err)
	}
	overrides, err := profile.DecodeOverrides(overridesJSON)
	if err != nil {
		fatalf("decode reviewed WAF overrides: %v", err)
	}
	sort.Slice(overrides.Resources, func(i, j int) bool {
		return overrides.Resources[i].TerraformName < overrides.Resources[j].TerraformName
	})

	var source bytes.Buffer
	fmt.Fprintf(&source, "// %s\n\npackage generator\n\n", generatedMarker)
	source.WriteString("var reviewedDocsExamples = map[string]string{\n")
	for _, resource := range overrides.Resources {
		module := strings.TrimPrefix(resource.TypeNameSuffix, "waf_")
		examplePath := filepath.Join(*root, "examples", "waf", module+".tf")
		example, err := os.ReadFile(examplePath)
		if err != nil {
			fatalf("read reviewed example for %s: %v", resource.TerraformName, err)
		}
		text := strings.TrimSpace(string(example)) + "\n"
		declaration := `resource "` + resource.TerraformName + `" "example"`
		if strings.Count(text, declaration) != 1 {
			fatalf("reviewed example %s must contain exactly one %s declaration", examplePath, declaration)
		}
		if strings.Count(text, `resource "fortiappseccloud_waf_`) != 1 {
			fatalf("reviewed example %s must contain exactly one WAF resource", examplePath)
		}
		fmt.Fprintf(&source, "\t%q: %s,\n", resource.TerraformName, strconv.Quote(text))
	}
	source.WriteString("}\n")

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		fatalf("format generated documentation examples: %v", err)
	}
	target := filepath.Join(*root, "internal", "generator", "docs_examples_generated.go")
	if err := os.WriteFile(target, formatted, 0o644); err != nil {
		fatalf("write generated documentation examples: %v", err)
	}
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "wafdocgen: "+format+"\n", args...)
	os.Exit(1)
}
