package generator

import (
	"terraform-provider-fortiappseccloud/internal/contract"
	profile "terraform-provider-fortiappseccloud/internal/generator/profile/waf"
)

const generatedMarker = "Code generated by cmd/wafgen; DO NOT EDIT."

// Manifest is the deterministic merged record of pinned source facts and
// reviewed Terraform policy for the selected vertical slice.
type Manifest struct {
	Generated string        `json:"generated"`
	OpenAPI   OpenAPISource `json:"openapi"`
	Scope     Scope         `json:"scope"`
	Resources []ResourceIR  `json:"resources"`
}

type OpenAPISource struct {
	Path    string `json:"path"`
	Version string `json:"version"`
	SHA256  string `json:"sha256"`
}

type Scope struct {
	Classification          string                             `json:"classification"`
	FullWAFClassification   bool                               `json:"full_waf_classification"`
	PublicOperationCount    int                                `json:"public_operation_count"`
	NonPublicOperationCount int                                `json:"non_public_operation_count"`
	SelectedResourceCount   int                                `json:"selected_resource_count"`
	NextGeneratedResource   *contract.ReviewedCandidate        `json:"next_generated_resource,omitempty"`
	Operations              []contract.OperationClassification `json:"operations"`
}

type ResourceIR struct {
	TerraformName string                   `json:"terraform_name"`
	GoName        string                   `json:"go_name"`
	Disposition   string                   `json:"disposition"`
	Source        OperationSource          `json:"source"`
	WireSchema    SchemaIR                 `json:"wire_schema"`
	Reviewed      profile.ResourceOverride `json:"reviewed_policy"`
}

type OperationSource struct {
	GetMethod              string `json:"get_method"`
	GetPath                string `json:"get_path"`
	GetResponseRef         string `json:"get_response_ref"`
	GetResultRef           string `json:"get_result_ref"`
	PutMethod              string `json:"put_method"`
	PutPath                string `json:"put_path"`
	PutRequestRef          string `json:"put_request_ref"`
	TemplateGetMethod      string `json:"template_get_method"`
	TemplateGetPath        string `json:"template_get_path"`
	TemplateGetResponseRef string `json:"template_get_response_ref"`
	TemplateGetResultRef   string `json:"template_get_result_ref"`
	TemplatePutMethod      string `json:"template_put_method"`
	TemplatePutPath        string `json:"template_put_path"`
	TemplatePutRequestRef  string `json:"template_put_request_ref"`
}

// SchemaIR contains only supported normalized JSON schema facts. Fields and
// enum values are sorted and duplicate-free before rendering.
//
// BackendEnriched marks a field injected by the generator from reviewed
// backend policy rather than the pinned OpenAPI document. BackendProvenance
// carries the reviewed provenance string for such fields. Both are omitted
// from JSON for pure OpenAPI fields so the manifest stays byte-identical for
// resources without backend additions.
type SchemaIR struct {
	Name      string   `json:"name,omitempty"`
	SourceRef string   `json:"source_ref,omitempty"`
	Kind      string   `json:"kind"`
	Required  bool     `json:"required"`
	ReadOnly  *bool    `json:"read_only,omitempty"`
	Default   any      `json:"default,omitempty"`
	Enum      []any    `json:"enum,omitempty"`
	Pattern   string   `json:"pattern,omitempty"`
	MinLength *int     `json:"min_length,omitempty"`
	MaxLength *int     `json:"max_length,omitempty"`
	Minimum   *float64 `json:"minimum,omitempty"`
	Maximum   *float64 `json:"maximum,omitempty"`
	MinItems  *int     `json:"min_items,omitempty"`
	MaxItems  *int     `json:"max_items,omitempty"`
	// Nullable records whether the pinned OpenAPI marks the schema nullable.
	// It is honored only for optional config scalars so a null remote value is
	// preserved as stable null state instead of a malformed-result error.
	Nullable          bool               `json:"nullable,omitempty"`
	Fields            []SchemaIR         `json:"fields,omitempty"`
	Items             *SchemaIR          `json:"items,omitempty"`
	CrossFieldRules   []CrossFieldRuleIR `json:"cross_field_rules,omitempty"`
	BackendEnriched   bool               `json:"backend_enriched,omitempty"`
	BackendProvenance string             `json:"backend_provenance,omitempty"`
}

// CrossFieldRuleIR is one validated x-fortinet-cross-field-v1 rule attached
// to an object schema. The v1 contract supports conditional integer ranges
// and integer comparisons, optionally guarded by boolean conditions.
type CrossFieldRuleIR struct {
	Kind     string                 `json:"kind"`
	Field    string                 `json:"field,omitempty"`
	Minimum  *int64                 `json:"minimum,omitempty"`
	Maximum  *int64                 `json:"maximum,omitempty"`
	Left     string                 `json:"left,omitempty"`
	Operator string                 `json:"operator,omitempty"`
	Right    string                 `json:"right,omitempty"`
	When     *CrossFieldConditionIR `json:"when,omitempty"`
}

// CrossFieldConditionIR is either one boolean equality leaf or a non-empty
// conjunction. Equals is a pointer so equals=false remains distinguishable
// from an omitted value during strict parsing and manifest serialization.
type CrossFieldConditionIR struct {
	Field  string                  `json:"field,omitempty"`
	Equals *bool                   `json:"equals,omitempty"`
	AllOf  []CrossFieldConditionIR `json:"all_of,omitempty"`
}
